### ISSUE TITLE
Promote AdoptOpenJDK Version jdk8u272-b10

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#179] opened 2020-10-22 10:52 UTC
Java Version:

JVM:
- [ ] OpenJ9
- [x] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by gdams** [comment] 2020-10-22 10:53
TRSS [link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f9066fd11d26031c11b07a9&testSummaryResult=failed&buildNameRegex=%5ETest) 
Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1309/ 
Started by user George Adams 
### ⚠️  [jdk8u-linux-s390x-hotspot](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-hotspot/731/) has a build result of ABORTED ⚠️

[**Test_openjdk8_hs_sanity.openjdk_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/216/) 
jdk_lang_0 => [deep history 10/11 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178711d26031c11d569c) - non-blocking java.lang.OutOfMemoryError - passes on rerun

[**Test_openjdk8_hs_sanity.external_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux/24/) - [quarkus_quickstarts test](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux_quarkus_quickstarts) fail, consistent with openj9 below, start failing around Oct 14th (seems like an environment change)

[**Test_openjdk8_hs_sanity.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/302/) 
jdk_jdi_0 => [deep history 0/11 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91070b11d26031c11cd767) - config issue JDWP exit error JVMTI_ERROR_INVALID_LOCATION(24): One or more of the library paths supplied to jdwp, likely by sun.boot.library.path, is too long. [linker_md.c:60]

[**Test_openjdk8_hs_sanity.openjdk_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-32_windows/275/) 
jdk_jdi_0 => [deep history 2/12 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2911d26031c11c8007) - same config issue as x64win above, passes on 2 ibm machines (test-ibmcloud-win2012r2-x64-1 & test-ibmcloud-win2012r2-x64-2) should look at the path on those machines to see differences

[**Test_openjdk8_hs_sanity.perf_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.perf_s390x_linux/24/) 
dacapo-h2_0 => [deep history 0/13 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f211d26031c120281a) - issue raised https://github.com/AdoptOpenJDK/openjdk-tests/issues/2028, will be non-blocking but would be good to see if last release jdk can be run without issue

[**Test_openjdk8_hs_extended.system_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.system_x86-64_mac/304/) 
HCRLateAttachWorkload_0 => [deep history 2/13 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c111d26031c11bcdb3) - well-known infra issue, https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1274

[**Test_openjdk8_hs_sanity.system_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_s390x_linux/334/) 
LambdaLoadTest_Hotspot_0 => [deep history 7/13 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f511d26031c12029a9) - intermittently fails with OOM error, needs issue raised

**Comment by smlambert** [comment] 2020-10-22 18:39
I updated the comment above to remove the 38 extra entries of jdk_jfr_0 test target.  Apparently Jenkins pushed the output to the console 39 times despite only 1 run of the test actually taking place (details here: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/321).

**Comment by smlambert** [comment] 2020-10-22 20:44
I've also moved all of the newly added tests failure reports to this comment (and out of the summary above which now only contains reports of the tests that we have used for previous releases).


[**Test_openjdk8_hs_extended.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_windows/16/) 
hotspot_jre_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd817) 
jdk_awt_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd81d) 
jdk_other_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd812) 
jdk_security1_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd815) 
jdk_security2_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd81f) 
jdk_security3_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd81b) 
jdk_management_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd810) 
jdk_jmx_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91071511d26031c11cd81a) 




[**Test_openjdk8_hs_special.functional_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_ppc64_aix/17/) 
MBCS_Tests_annotation_Ja_JP_aix_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178711d26031c11d5757) 

[**Test_openjdk8_hs_extended.openjdk_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-32_windows/6/) 
hotspot_jre_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c8025) 
jdk_awt_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c802f) 
jdk_other_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c8024) 
jdk_security1_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c802b) 
jdk_security2_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c8031) 
jdk_security3_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c802d) 
jdk_management_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c8022) 
jdk_jmx_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa2e11d26031c11c8028) 


[**Test_openjdk8_hs_extended.perf_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.perf_s390x_linux/1/) 
renaissance-als_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027e9) 
renaissance-chi-square_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027ee) 
renaissance-db-shootout_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027de) 
renaissance-dec-tree_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027e6) 
renaissance-gauss-mix_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027ef) 
renaissance-log-regression_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027df) 
renaissance-movie-lens_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027e3) 
renaissance-par-mnemonics_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027eb) 
renaissance-philosophers_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163f111d26031c12027f0) 

[**Test_openjdk8_hs_extended.openjdk_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_s390x_linux/7/) 

[**Test_openjdk8_hs_extended.openjdk_ppc64le_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux/2/) 
hotspot_jre_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63c0) 
jdk_awt_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63c5) 
jdk_other_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63b0) 
jdk_security1_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63bc) 
jdk_security3_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63b1) 
jdk_security4_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63c7) 
jdk_management_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63c8) 
jdk_tools_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63b8) 
jdk_jfr_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63b3) 
jdk_2d_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63bf) 
Post Test => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8fc11d26031c11b63b9) 

[**Test_openjdk8_hs_extended.perf_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.perf_x86-32_windows/1/) 
renaissance-als_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa3211d26031c11c80dc) 
renaissance-chi-square_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa3211d26031c11c80e5) 
renaissance-db-shootout_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa3211d26031c11c80d4) 
renaissance-dec-tree_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa3211d26031c11c80d9) 
renaissance-gauss-mix_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa3211d26031c11c80e6) 
renaissance-log-regression_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa3211d26031c11c80d5) 
renaissance-movie-lens_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90fa3211d26031c11c80e2) 


[**Test_openjdk8_hs_extended.external_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.external_s390x_linux/3/) 
kafka_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202a9e) 
example-test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202ab9) 
WycheproofTests_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202aa5) 
quarkus_java_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202aa0) 
lucene_solr_nightly_smoketest_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202aad) 
tomcat_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202abc) 
wildfly_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202ab5) 
camel_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202aa8) 
jenkins_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202aa3) 
scala_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9163fb11d26031c1202abe) 

[**Test_openjdk8_hs_extended.openjdk_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_mac/6/) 
hotspot_jre_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce4f) 
jdk_other_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce50) 
jdk_security1_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce4b) 
jdk_security3_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce51) 
jdk_management_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce47) 
jdk_tools_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce42) 
jdk_jfr_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce53) 
jdk_instrument_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce48) 
jdk_imageio_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce3d) 
jdk_2d_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90d8c611d26031c11bce4e) 

[**Test_openjdk8_hs_extended.openjdk_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64_aix/2/) 
hotspot_jre_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d5640) 
jdk_awt_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d564c) 
jdk_other_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d564d) 
jdk_security1_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d5636) 
jdk_security3_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d564e) 
jdk_security4_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d561f) 
jdk_tools_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d562c) 
jdk_jfr_0 => [deep history 0/39 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91178511d26031c11d5650) 


[**Test_openjdk8_hs_extended.external_ppc64le_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.external_ppc64le_linux/19/) 
WycheproofTests_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6360) 
lucene_solr_nightly_smoketest_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6361) 
quarkus_java_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b635b) 
tomcat_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6362) 
wildfly_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6363) 
example-test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6370) 
scala_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6377) 
jenkins_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6371) 
kafka_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b6365) 
camel_test_0 => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f90b8f811d26031c11b635f) 

[**Test_openjdk8_hs_extended.perf_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.perf_ppc64_aix/1/) 
Post Test => [deep history 0/1 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f9116f511d26031c11d55d9)

**Comment by lumpfish** [comment] 2020-10-23 08:25
openj9 test results (excluding failures from the newly added tests) from run https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1311/

ppc64_aix - all passed
ppc64le_linux - all passed
ppc64le_linux_xl - all passed
s390x_linux - all passed
s390x_linux_xl - all passed
x86-32_windows - **one failure, raised https://github.com/eclipse/openj9/issues/10975**
x86-64_linux - **Not all test jobs were submitted, resubmitted via https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1316/**
x86-64_linux_xl - **Not all test jobs were submitted, resubmitted via https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1316/**
x86-64_mac - all passed
x86-64_mac_xl - all passed
x86-64_windows - all passed
x86-64_windows_xl - all passed

**Comment by lumpfish** [comment] 2020-10-23 12:46
openj9 results from rebuild job https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1316/

x86-64_linux
Three failures from sanity.external
quarkus_quickstarts_test_0: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_quarkus_quickstarts/109/
openliberty_microprofile_tck_jdk8_j9: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_openliberty-mp-tck/432/
tomee_test_j9_0: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_tomee/390/
All other tests passed

x86-64_linux_xl - all tests passed

**Comment by smlambert** [comment] 2020-10-23 13:47
It is disconcerting that the sanity.external targets had been 'healthier' up until very recently.  It appears that some 'event' occurs on Oct 14th that causes each of these to no longer run properly.

I see that quarkus_quickstarts passing until Oct 14 (consistent with the last healthy [hotspot run](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux_quarkus_quickstarts/15/console)).

tomee running all tcks but failing on last one, then at Oct 14 no longer executing in the same way.  

Did we publish a bunch of new Docker images or in some other way change the environment around that Oct 14th time frame?

**Do not think we would block on these external test failures**, but it will be good to understand what event may cause the behaviour change.

**Comment by sxa** [comment] 2020-10-23 14:00
Agreed @smlambert 
Doesn't look like the failure is on a new machine although it took me a while to find the last one that ran on the same machine:
Passing run: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_quarkus_quickstarts/101/consoleFull
Failing run: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_quarkus_quickstarts/109/consoleFull
Both on https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-3/
I'm not aware of any changes that have been put on those systems recently.

**Comment by smlambert** [comment] 2020-10-23 14:07
There has not been any suspect PRs in openjdk-tests repo from that timeframe.

There seems to be a lot of activity in openjdk-docker repo from 9-10 days ago, though I am not sure if they are suspects or not:
<img width="888" alt="Screen Shot 2020-10-23 at 10 04 13 AM" src="https://user-images.githubusercontent.com/2836948/97013712-5cc86480-1517-11eb-8b6a-ac08ac27569c.png">

We run external tests by pulling the AdoptOpenJDK images tagged 'nightly' and mapping the nightly or upstream JDK to run the test suites that get set up in the container.

**Comment by gdams** [comment] 2020-10-23 14:35
JDK8u re-run:

TRSS [link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f92c0a411d26031c1306eb8&testSummaryResult=failed&buildNameRegex=%5ETest) 
Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1317/ 
Started by user George Adams 

[**Test_openjdk8_hs_sanity.external_x86-64_linux_quarkus_quickstarts**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_x86-64_linux_quarkus_quickstarts/94/) 
quarkus_quickstarts_test_0 => [deep history 1/2 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f92da6b11d26031c130c3e2) 

[**Test_openjdk8_hs_sanity.external_x86-64_linux_openliberty-mp-tck**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_x86-64_linux_openliberty-mp-tck/517/) 
openliberty_microprofile_tck_jdk8_hs_0 => [deep history 0/2 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f92da6e11d26031c130c417) 

[**Test_openjdk8_hs_sanity.external_x86-64_linux_tomee**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_x86-64_linux_tomee/471/) 
tomee_test_hs_0 => [deep history 1/2 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f92da6a11d26031c130c3cb) 

[**Test_openjdk8_hs_sanity.external_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_x86-64_linux/538/)

**Comment by gdams** [comment] 2020-10-23 14:47
JDK8u re-run:

TRSS [link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f91d41411d26031c124fbfe&testSummaryResult=failed&buildNameRegex=%5ETest) 
Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1315/ 
Started by user George Adams 

[**Test_openjdk8_hs_sanity.openjdk_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-32_windows/278/) 
jdk_jdi_0 => [deep history 2/10 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91e21511d26031c125ca50) 

[**Test_openjdk8_hs_sanity.external_s390x_linux_quarkus_quickstarts**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux_quarkus_quickstarts/23/) 
quarkus_quickstarts_test_0 => [deep history 2/8 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f92d8e711d26031c130c0c1) 

[**Test_openjdk8_hs_sanity.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/305/) 
jdk_jdi_0 => [deep history 0/9 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f91ec3e11d26031c1267389) 

[**Test_openjdk8_hs_sanity.perf_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.perf_s390x_linux/26/) 
dacapo-h2_0 => [deep history 0/9 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f92d86811d26031c130c041) 

[**Test_openjdk8_hs_sanity.external_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux/26/) 

[**Test_openjdk8_hs_sanity.perf_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.perf_x86-32_windows/25/) 

[**Test_openjdk8_hs_extended.system_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.system_x86-64_mac/307/) 
HCRLateAttachWorkload_0 => [deep history 2/9 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f92334211d26031c12b9ca7) 

[**Test_openjdk8_hs_sanity.system_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_x86-32_windows/25/)

**Comment by andrew-m-leonard** [comment] 2020-10-23 15:32
Running a Grinder on the openj9 win32 jdk/test/java/lang/ProcessBuilder/Basic.java failure just to check it was a machine issue:
https://ci.adoptopenjdk.net/job/Grinder/4287/
**Green**

**Comment by andrew-m-leonard** [comment] 2020-10-23 15:42
jdk8u272-b10_openj9-0.23.0: Pipelines for publishing:
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1311/

**Comment by gdams** [comment] 2020-10-23 15:51
HotSpot shipped except for aarch64 - @smlambert approved the release

**Comment by gdams** [comment] 2020-10-23 15:59
Aarch64 pipeline complete: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-hotspot/691/

TRSS [link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f92c43c11d26031c130777f&testSummaryResult=failed&buildNameRegex=%5ETest) 
Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1318/ 
Started by user George Adams 


No failures

**Comment by gdams** [comment] 2020-10-23 16:02
Aarch64 HotSpot shipped - @karianna approved the release

**Comment by andrew-m-leonard** [comment] 2020-10-23 17:28
OpenJ9 jdk8 shipped.

**Comment by gdams** [comment] 2020-10-24 11:49
OpeJ9 macOS re-run:

TRSS [link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f93454311d26031c1312bee&testSummaryResult=failed&buildNameRegex=%5ETest) 
Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1321/ 
Started by user George Adams 

NO FAILURES

**Comment by gdams** [comment] 2020-10-27 09:54
HotSpot Linux Arm32:

TRSS [link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f97499411d26031c13c1aaf&testSummaryResult=failed&buildNameRegex=%5ETest) 
Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1326/ 
Started by user George Adams 

[**Test_openjdk8_hs_sanity.openjdk_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/70/) 
jdk_util_0 => [deep history 1/7 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f97a6a911d26031c13d61c9) 
jdk_jdi_0 => [deep history 5/7 passed](https://trss.adoptopenjdk.net/deepHistory?testId=5f97a6a911d26031c13d61cc)

**Comment by smlambert** [comment] 2020-10-27 14:13
jdk_util failure was a timeout on [CountLargeTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/71/testReport/java_util_stream_test_org_openjdk_tests_java_util_stream_CountLargeTest/) (which passes on rerun but is a long execution time 7+ minutes, so it will likely continue to hit timeout on occasion)

jdk_jdi tests seem to be machine related, as they all pass on rerun [here](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_arm_linux/72/testReport/) / running on test-sxamb-armv7l-raspbian-pi4

**Comment by gdams** [comment] 2020-10-28 09:48
Solaris HotSpot pipeline: 

TRSS [link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f98b3ef7702786daf5fd758&testSummaryResult=failed&buildNameRegex=%5ETest) 
Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1330/ 
Started by user George Adams 

NO TESTS RUN ON SOLARIS (we never have)

**Comment by sxa** [comment] 2020-10-28 10:35
@gdams To be clear to reviewers/approvers is "NO TEST FAILURES" your way of saying we haven't run any tests, or have you run some somewhere outside the pipelines?

**Comment by gdams** [comment] 2020-10-28 10:38
@sxa that is true, updating the comment

**Comment by sxa** [comment] 2020-10-28 11:26
Thanks for clarifying - I approve this going out now on the basis it's undergone the same level as testing as on previous releases (We need to change this though!) :-)

**Comment by andrew-m-leonard** [comment] 2020-10-29 11:34
Release build for jdk8u272-b10_openj9-0.23.0 for aarch64 “ea” started:
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1333/

**Comment by andrew-m-leonard** [comment] 2020-10-29 15:06
jdk8u272-b10_openj9-0.23.0 for aarch64 “ea” test results, "All Green" :-) : 
https://trss.adoptopenjdk.net/resultSummary?parentId=5f9aaae57702786daf8c1e91

**Comment by sxa** [comment] 2020-10-29 15:12
> jdk8u272-b10_openj9-0.23.0 for aarch64 “ea” test results, "All Green" :-) :
> https://trss.adoptopenjdk.net/resultSummary?parentId=5f9aaae57702786daf8c1e91

I approve on the basis of that and the fact that Andrew has confirmed the metadata looks ok. Let's ship it and see if the website picks it up properly.

```
12:17:22      "version": {
12:17:22          "minor": 0,
12:17:22          "security": 272,
12:17:22          "pre": "ea",
12:17:22          "adopt_build_number": null,
12:17:22          "major": 8,
12:17:22          "version": "1.8.0_272-ea-b10",
12:17:22          "semver": "8.0.272-ea+10",
12:17:22          "build": 10,
12:17:22          "opt": null
12:17:22      },
```

**Comment by smlambert** [comment] 2020-10-29 15:17
+1 to releasing jdk8u272-b10_openj9-0.23.0 for aarch64 “ea”

**Comment by karianna** [comment] 2020-10-29 16:26
Ship it! :-)

**Comment by sxa** [comment] 2020-10-30 11:40
Live and working. And since that was the last platform on JDK8u272 I'm going to close this :-)

**Closed as completed by sxa** 2020-10-30 11:40 UTC
Labels: enhancement
