### ISSUE TITLE
Import AArch64 binary packages

### ISSUE THREAD

**Issue by theRealAph** [AdoptOpenJDK/TSC#22] opened 2018-04-27 13:00 UTC
As the leader of the OpenJDK AArch64 port project, I'd like to make packages available to Adopt OpenJDK. They would be fully TCK'd and JTreg regression tested, and built at Red Hat.

- [] 1. Add the aarch64 binary to the `openjdk{version}-releases` repository for storing releases.
- [] 2. Add meta data to the website to indicate aarch64 build is supplied by Red Hat.
- [] 3. Add meta data to the api to indicate aarch64 build is supplied by Red Hat.

**Comment by karianna** [comment] 2018-04-27 13:43
@theRealAph Thanks Andrew, they'd be a welcome addition I suspect!  The Adopt Build Farm is open to running it's 3rd party tests on pre built binaries (assuming we have enough spare capacity).  Are you the right person to co-ordinate with on the technical details on getting this to work?

What will likely happen is that we create pipelines to retrieve the binaries, run our 3rd party tests and (assuming they pass) store them in the appropriate releases repo where they are then automatically made available in the website and through the API gateway.

We're still working on overhauling the website, but one of the things we could offer is to provide a link to Red Hat support for those looking for commercial support of those binaries.  Let me know if that's useful to you.

**Comment by tellison** [comment] 2018-04-27 18:19
Yep, I agree with @karianna, we'd need an automated way to pull down the builds from Red Hat's repo and then put them through our release testing before hosting them as 'releases' on the AdoptOpenJDK site.

We have [good capacity on AArch64](https://ci.adoptopenjdk.net/label/aarch64/load-statistics) so I don't foresee that as a problem.

We'd have to figure out if these Red Hat builds sit alongside or replace [the AArch64 builds that we are running](https://ci.adoptopenjdk.net/view/arm/).

**Comment by gdams** [comment] 2018-04-27 18:42
@karianna are we legally okay claiming TCK compliance on binaries that we haven't personally run the test suite on?

**Comment by theRealAph** [comment] 2018-04-27 19:49
I don't think that there's any need to claim anything. We should use the TCK to check compliance and if anyone asks, we say that we run the TCK. Claiming Java compliance requires a trade mark agreement, anyway, and we don't have that.

**Comment by karianna** [comment] 2018-04-27 22:14
@tellison I think we use Red Hat's binaries initially and then have a discussion about building from source together as such.

**Comment by judovana** [comment] 2018-05-03 13:52
Practical details:
Which forest do you wont to provide builds for?
 * http://hg.openjdk.java.net/jdk-updates/jdk10u/
 * http://hg.openjdk.java.net/aarch64-port/jdk8u/
 * http://hg.openjdk.java.net/aarch64-port/jdk8u-shenandoah/

Are you interested only for10 ? Or do you wont to include also 8u? If 8 is in play, I would vote for dk8u-shenandoah/, as it is abit more often tested.

**Comment by judovana** [comment] 2018-05-03 13:53
In all cases, all three can be provided. But adopt-openjdk is not ready to be real multi-project  jdk provider.
Regards,
   Jiri

**Comment by judovana** [comment] 2018-05-03 13:59
Also, Are you intereste donly of builds in aarch64 or on intels and windows?
I can provide:
 aarch64 binaries built in rhel7
x86_64  binaries built in rhel6
i686  binaries built in rhel6

We have also windows build, but it can be blocekd  to be publicy released by license of hosts
No macs available, however souce tarball can be provided so it canbe rebuilt.

**Comment by karianna** [comment] 2018-05-03 14:53
I think you'll want to check with Andrew as to exactly which binaries he
wants to go through Adopt pipelines.

Cheers,
Martijn

**Comment by theRealAph** [comment] 2018-05-03 15:09
On 05/03/2018 03:53 PM, Martijn Verburg wrote:
> I think you'll want to check with Andrew as to exactly which binaries he
> wants to go through Adopt pipelines.

Whatever you want of what we have.

-- 
Andrew Haley
Java Platform Lead Engineer
Red Hat UK Ltd. <https://www.redhat.com>
EAC8 43EB D3EF DB98 CC77 2FAD A5CD 6035 332F A671

**Comment by judovana** [comment] 2018-05-03 15:54
ok. I will uploaded our latest jdk10 binaries, and one of hte latest (closest to latest tag) aarch64-shenandoah binaries.

**Comment by karianna** [comment] 2018-05-03 15:57
Let's start with that, work out the mechanics and then we'll do a gap analysis of what else we are missing.  Thanks!

**Comment by judovana** [comment] 2018-05-07 14:10
https://jvanek.fedorapeople.org/java-10-openjdk/
https://jvanek.fedorapeople.org/java-1.8.0-openjdk/

Both signed, and verifiable via fingerprint of
  C058 EF1E 7498 12E6 A486  384B 53B5 CFF6 71EE ED59

Both those builds are still subject of testing
I can provide fastdebug builds if necessary (also tested) but  run out of space on fedorapeople.

**Comment by judovana** [comment] 2018-05-09 15:54
Jdk8 re-testing is done. It is perfectly ok to go.
jdk10 re-testing is done. It is ok, except 7 failing kerberos tests.  They should be caused by misconfiguration on my side. Please speed up the upload if possible.

**Comment by karianna** [comment] 2018-05-21 14:18
We're going with an alternative strategy to calssifying these as variants.  @gdams is going to take over and get this out.

**Comment by karianna** [comment] 2019-04-21 15:26
@theRealAph and @jerboaa - Did you want to make these available through the new upstream builds mechanism?

**Comment by jerboaa** [comment] 2019-04-23 07:58
@karianna Yes. Work is under way to have Linux aarch64 builds available for the next CPU cycle. They'll be JDK 11 only for now as jdk8u upstream doesn't have an AArch64 hotspot port included in mainline.

**Comment by karianna** [comment] 2019-04-23 08:08
OK, I'll close this issue as we're naturally happy to support this.  As with the other issue, we'll include these binaries in the APIv3 overhaul in due course.

**Closed as completed by karianna** 2019-04-23 08:08 UTC
Labels: enhancement

**Comment by jerboaa** [comment] 2019-05-08 10:05
FYI: Linux aarch64 JDK 11 builds are now available for interested parties:
https://adoptopenjdk.net/upstream.html
