### ISSUE TITLE
Promote AdoptOpenJDK Version jdk8u242-b08

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#135] opened 2020-01-20 09:21 UTC
Java Version: jdk8u242-b08

JVM:
- [x] OpenJ9
- [x] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

All hotspot platforms triggered: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/830/

**Comment by gdams** [comment] 2020-01-20 09:21
Aarch64 linux failed because the tag hadn't been mirrored: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-hotspot/371/console

**Comment by gdams** [comment] 2020-01-20 09:30
**Test Failures**

**Linux x64**
**sanity.system:**
TestJlmRemoteMemoryAuth_SE80_Linux_0 => Known intermittent failure upstream https://github.com/AdoptOpenJDK/TSC/issues/135#issuecomment-576196497

**sanity.external:** => Test issues (non blocking https://github.com/AdoptOpenJDK/TSC/issues/135#issuecomment-576273558)
tomee_test_0
thorntail_microprofile_tck_0

**Linux s390x**
**extended.system:**
UtilLoadTest_0 => Long term failure (https://github.com/AdoptOpenJDK/TSC/issues/135#issuecomment-576280729) 

**Aix**
**sanity.openjdk:**
java/nio/channels/AsynchronousSocketChannel/StressLoopback.java => (passed on re-run [grinder](https://ci.adoptopenjdk.net/job/Grinder/1805/))
java/nio/file/WatchService/DeleteInterference.java => (passed on re-run [grinder](https://ci.adoptopenjdk.net/job/Grinder/1805/))
java/nio/file/WatchService/LotsOfCancels.java => (passed on re-run [grinder](https://ci.adoptopenjdk.net/job/Grinder/1805/))
sun/rmi/transport/tcp/DeadCachedConnection.java => (passed on re-run [grinder](https://ci.adoptopenjdk.net/job/Grinder/1807/))

**Comment by jerboaa** [comment] 2020-01-20 09:56
> **Test Failures**
> 
> **Linux x64**
> **sanity.system:**
> TestJlmRemoteMemoryAuth_SE80_Linux_0

This one is:
```
Exception in thread "main" java.lang.AssertionError: Peak Usage used memory smaller than Current Usage used memory
```

We see this intermittently with upstream builds too. I haven't investigated any further. It's not a new issue at all, though. => should not be release blocking.

**Comment by smlambert** [comment] 2020-01-20 13:25
sanity.external:
thorntail mp tck error - Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.9.0/jackson-jaxrs-json-provider-2.9.0.pom from http://repo1.maven.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.9.0/jackson-jaxrs-json-provider-2.9.0.pom

Seems to have failed intermittently ([deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e2555cf291346186002cf10)), some of those times with connectivity issues.  

tomee mp tck:
10:19:20  [INFO] TomEE :: Gradle Plugins ............................ FAILURE [  0.355 s]
10:19:20  [ERROR] Failed to execute goal on project gradle: Could not resolve dependencies for project org.apache.tomee.gradle:gradle:pom:8.0.2-SNAPSHOT: Failed to collect dependencies at org.gradle:gradle-core:jar:3.0: Failed to read artifact descriptor for org.gradle:gradle-core:jar:3.0: Could not transfer artifact org.gradle:gradle-core:pom:3.0 from/to gradle-libs-releases-local (http://repo.gradle.org/gradle/libs-releases-local/): Access denied to: http://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-core/3.0/gradle-core-3.0.pom , ReasonPhrase:Forbidden. -> [Help 1]

Seems to be a new failure, again on the test side.  Will see if it reproduces.

For both sanity.external failures, they seem to be an issue on the test side, so consider non-blocking.  I can rerun.   We will have to think about how to make these tests more consistent (right now we build off tip rather than last stable release of those projects, so will likely change that behaviour for a start).

**Comment by smlambert** [comment] 2020-01-20 13:44
> Linux s390x
extended.system:
UtilLoadTest_0

A very consistent failure ([deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e25553e291346186002cdc1)) on s390x.  Failing over visible history...  going to rerun against last release to see behaviour (rerun Grinder on Oct release here: [Grinder 1804](https://ci.adoptopenjdk.net/job/Grinder/1804)).

Update: Grinder 1804 also failed UtilLoadTest using October release.  This means its not a regression, and we have already released with this failure present.  Consider non-blocking, but would like someone to take a much closer look at this issue before next release.

**Comment by smlambert** [comment] 2020-01-20 14:00
We do not have a lot of history on AIX, as we have not had test machines for very long.  I suspect both the jdk_nio and jdk_rmi failures to be an infra issue, and we can try on another machine to see behaviour.

Aix
sanity.openjdk:
- jdk_nio: Failing with timeouts
java/nio/channels/AsynchronousSocketChannel/StressLoopback.java
java/nio/file/WatchService/DeleteInterference.java
java/nio/file/WatchService/LotsOfCancels.java

- jdk_rmi:  sun/rmi/transport/tcp/DeadCachedConnection.java

[2020-01-20T07:03:21.882Z] JAVAVM: command = [/ramdisk0/build/workspace/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/jre/bin/java, sun.rmi.registry.RegistryImpl, 48190]
[2020-01-20T07:03:21.882Z] Trying to use registry in spite of stale cache...
[2020-01-20T07:03:21.882Z] java.rmi.ConnectException: Connection refused to host: 140.211.9.10; nested exception is: 
[2020-01-20T07:03:21.882Z] 	java.net.ConnectException: A remote host refused an attempted connect operation. (Connection refused)
[2020-01-20T07:03:21.882Z] 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)

Grinder to rerun jdk_rmi target:

**Comment by jerboaa** [comment] 2020-01-21 08:26
> > Linux s390x
> > extended.system:
> > UtilLoadTest_0
> 
> A very consistent failure ([deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e25553e291346186002cdc1)) on s390x. Failing over visible history... going to rerun against last release to see behaviour (rerun Grinder on Oct release here: [Grinder 1804](https://ci.adoptopenjdk.net/job/Grinder/1804)).

I've noticed that s390x is using Zero for the hotspot build on JDK 8. That's actually expected as the JIT port got introduced later on. However, this means it's using the cpp interpreter which is quite slow. It might well be this is a timeout/slowness issue.

```Full thread dump OpenJDK 64-Bit Zero VM (25.232-b09 interpreted mode):```

**Comment by gdams** [comment] 2020-01-21 09:52
`aarch64-shenandoah-jdk8u242-b08` hasn't been merged into https://hg.openjdk.java.net/aarch64-port/jdk8u-shenandoah/jdk/ yet. This will slow down the aarch64 build.

**Comment by gdams** [comment] 2020-01-21 10:09
@AdoptOpenJDK/tsc can somebody give me a +1 to release jdk8u242-b08 on all platforms (except arm and aarch64)

**Comment by jerboaa** [comment] 2020-01-21 10:12
+1

**Comment by gdams** [comment] 2020-01-21 10:14
jdk8u242-b08 hotspot on all platforms (except arm and aarch64) has now been released. Aarch64 and arm32 will follow shortly.

**Comment by adam-thorpe** [comment] 2020-01-21 11:54
We're currently triaging failures for jdk8u242-b08_openj9-0.18.0 here: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1567

**Comment by smlambert** [comment] 2020-02-24 14:01
jdk8u242-b08 hotspot aarch64 - looks good (test runs pass)

Build job: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-hotspot/405

Test jobs:
- [x] sanity.openjdk: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_aarch64_linux/138/

- [x] special.openjdk: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.openjdk_aarch64_linux/50/

- [x] sanity.system: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_aarch64_linux/131/

- [x] extended.system: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.system_aarch64_linux/131/

**Comment by sxa** [comment] 2020-02-24 18:40
8u242-b08/aarch64 now on https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u242-b08 after approval from @smlambert in the release channel.

@andrew-m-leonard also released AIX HotSpot JDK13 last week

**Comment by sxa** [comment] 2020-03-05 19:12
arm32 has been reverted to using the main jdk8u codebase and I'll try and get [an 8u242 out](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot/167) on that platform using the Zero VM (same as previous versions) until we can resolve the issues with the aarch32 repo.

**Comment by smlambert** [comment] 2020-03-06 17:03
I've attempted to launch [some testing](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2444/) against that arm32 build, but the single build/test machine we have https://ci.adoptopenjdk.net/label/hw.arch.aarch32/ is offline.

**Comment by smlambert** [comment] 2020-03-06 20:03
Thanks @sxa555 for relabeling some build machines for test for the arm32 testing.  I will relaunch some tests and report (much) later on the results (no JIT, will take time).

sanity.openjdk (expecting some natives to fail, as I did not provide native test libs): https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2453 - [8 failures](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2453/testReport/), 1538 run 
- 6 of the 8 failures are time outs (explained due to no JIT)
- [java_net_URL_OpenStream](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2453/testReport/java_net_URL_OpenStream/java/OpenStream/) fails with "Expected UnknownHostException to be thrown"
- [java_nio_MappedByteBuffer_Truncate](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2453/testReport/java_nio_MappedByteBuffer_Truncate/java/Truncate/) fails with message, try "ulimit -c unlimited" to enable core dumps

sanity.system: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2452/ - timeout, rerun with longer time limit

extended.system: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2454 - timeout, rerun with longer time limit

**Comment by sxa** [comment] 2020-03-07 13:16
@smlambert Looks like all of them hit a ten hour timeout :-)

**Comment by smlambert** [comment] 2020-03-08 00:48
Reruns of the system tests for arm32 with larger timeouts here:
sanity.system: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2455/
extended.system: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2456

**Comment by M-Davies** [comment] 2020-03-09 10:20
OpenStream and Truncate are being tracked in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1637 and https://github.com/AdoptOpenJDK/openjdk-tests/issues/1052 respectively. 

All the system tests look like timeouts again. There doesn't seem to be any relevant history of the failed tests on any platforms and without a JIT, the tests may not tear down their processes quick enough.

**Comment by sxa** [comment] 2020-03-09 18:26
@smlambert Not sure what you're view is on these - are the system test failures acceptable if they are timeouts on a zero VM? Any idea if we've run them before on this platform? If those are the only issues we should probably let it go out

**Comment by smlambert** [comment] 2020-03-09 20:32
Yes, my view is release the arm32 build.  It did surprisingly well, considering there is no JIT and we did not attempt to tune timeouts in any way.

**Comment by sxa** [comment] 2020-03-10 20:33
It's in https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u242-b08 now but not yet showing up on [the website](https://adoptopenjdk.net/releases.html) (I thought it would have by now as I promoted it a while ago ...)

**Comment by sxa** [comment] 2020-03-13 17:28
Now resolved. Closing as all platforms/variants are out now

**Closed as completed by sxa** 2020-03-13 17:28 UTC
Labels: enhancement
