### ISSUE TITLE
Promote AdoptOpenJDK Version jdk-15.0.2+7_openj9-0.24.0

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/TSC#200] opened 2021-01-21 13:53 UTC
JVM:
- [ ] OpenJ9

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by lumpfish** [comment] 2021-01-21 15:59
Triage results are being collated in: https://docs.google.com/document/d/1Xc3XTma_tIgD7re1IzXBMEPC4WTQajS4u7CsyA8SlRM/edit

**Comment by andrew-m-leonard** [comment] 2021-01-22 16:04
jdk-15.0.2+7_openj9-0.24.0 triage

Format is:

TRSS: Link to a TRSS set of tests (so normally one for aarch64 and one for everything else)
Platform (x86-64_linux, etc)
Link to job containing failed tests
List of failed targets, for openjdk tests, the individual failed tests
Any other information (links to issues for the failures, links to any reruns, discussion of the failures)


TRSS: 

https://trss.adoptopenjdk.net/resultSummary?parentId=600935222bad78506654abc3
aarch64_linux & xl (early access)
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_aarch64_linux/146/
Failed target / test:
jdk_lang_j9_0
TEST: java/lang/constant/MethodTypeDescTest.java
Re-run: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_aarch64_linux/148/
Passed

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.system_aarch64_linux/139/
Failed target:
ConcurrentLoadTest_0
HCRLateAttachWorkload_previewEnabled_0
Already known issues:
https://github.com/eclipse/openj9/issues/8493
https://github.com/eclipse/openj9/issues/10812


TRSS: https://trss.adoptopenjdk.net/resultSummary?parentId=600935222bad78506654abc5
ppc64_aix
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/172/console
Failed target / test:
jdk_lang_j9_0
TEST: java/lang/ProcessBuilder/Basic.java#id0
Re-run: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/174/
Raised issue: https://github.com/eclipse/openj9/issues/11738



https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_ppc64_aix/62/
Re-run: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_ppc64_aix/66/
ppc64le_linux
No blocking failures
ppc64le_linux_xl
No blocking failures
s390x_linux
No blocking failures
s390x_linux_xl
No blocking failures
x86-64_linux
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_x86-64_linux/162/console
Failed targets / tests:
jdk_foreign_0
TEST: java/foreign/TestMismatch.java
Raised new issue: https://github.com/eclipse/openj9/issues/11732

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_x86-64_linux/64/console
Failed target:
testDDRExt_Class_0
Raised new issue: https://github.com/eclipse/openj9/issues/11733
X86-64_linux_xl
TEST: java/foreign/TestMismatch.java
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_x86-64_linux_xl/160/
Re-run: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_x86-64_linux_xl/162/
Passed



x86-64_mac

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.functional_x86-64_mac/61/
Failed targets:
cmdLineTester_callsitedbgddrext_openj9_0
cmdLineTester_pltest_osx_0
cmdLineTest_sigabrtHandlingTest_0
Already raised defects: https://github.com/AdoptOpenJDK/run-aqa/issues/50, https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282
Rerun on pre mac 10.14 machine (test-macstadium-macos1013-x64-1): https://ci.adoptopenjdk.net/job/Grinder/6017/ - Tests PASSED except for cmdLineTest_sigabrtHandlingTest_0
UnsatisfiedLinkError: Can't load gptest
Issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2178
Re-run on 1010: https://ci.adoptopenjdk.net/job/Grinder/6034/console
Passed

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_x86-64_mac/61/
Failed targets:
testJcmd_0
testDDRExt_General_0
testDDRExt_Class_0
testDDRExt_Callsites_0
testDDRExt_JITExt_0
testDDRExt_SharedClasses_0
testDDRExtJunit_CollisionResilientHashtable_0
testDDRExtJunit_StackMap_0
testDDRExtJunit_MonitorsAndDeadlock1_1
testDDRExtJunit_MonitorsAndDeadlock2_1
testDDRExtJunit_MonitorsAndDeadlock3_1
testDDRExtJunit_MonitorsAndDeadlock4_1
testDDRExtJunit_MonitorsAndDeadlock5_1
testDDRExtJunit_MonitorsAndDeadlock6_1
testDDRExtJunit_FindExtThread_0
testSCCMLTests2_1
testSCCMLTests4_1
cmdLineTester_classesdbgddrext_1
cmdLineTester_modularityddrtests_1
cmdLineTester_shrcdbgddrext_1
cmdLineTester_dumpromclasstests_0
testOpenJ9DiagnosticsMXBean_0
Already raised defects: https://github.com/AdoptOpenJDK/run-aqa/issues/50, https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282
Rerun on pre mac 10.14 machine (test-macstadium-macos1013-x64-1): https://ci.adoptopenjdk.net/job/Grinder/6018/ - All PASSED except for cmdLineTester_modularityddrtests_1
Re-run: https://ci.adoptopenjdk.net/job/Grinder/6033/
Raised new issue: https://github.com/eclipse/openj9/issues/11739


x86-64_mac_xl
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.functional_x86-64_mac_xl/58/console
Failed targets:
cmdLineTest_sigabrtHandlingTest_0
Already known issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2178
Rerun on different test machine (test-macincloud-macos1010-x64-2): https://ci.adoptopenjdk.net/job/Grinder/6025/console - PASSED

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_x86-64_mac_xl/58/console
Failed targets:
cmdLineTester_classesdbgddrext_0
cmdLineTester_dumpromclasstests_0
cmdLineTester_modularityddrtests_0
testSCCMLTests2_0
testSCCMLTests4_0
cmdLineTester_shrcdbgddrext_0
testDDRExt_General_0
testDDRExt_Class_0
testDDRExt_Callsites_0
testDDRExt_JITExt_0
testDDRExt_SharedClasses_0
testDDRExtJunit_CollisionResilientHashtable_0
testDDRExtJunit_StackMap_0
testDDRExtJunit_MonitorsAndDeadlock1_0
testDDRExtJunit_MonitorsAndDeadlock2_0
testDDRExtJunit_MonitorsAndDeadlock3_0
testDDRExtJunit_MonitorsAndDeadlock4_0
testDDRExtJunit_MonitorsAndDeadlock5_0
testDDRExtJunit_MonitorsAndDeadlock6_0
testDDRExtJunit_FindExtThread_0
TestJcmd_0
testOpenJ9DiagnosticsMXBean_0
Already raised defects: https://github.com/AdoptOpenJDK/run-aqa/issues/50, https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282
Rerun on pre mac 10.14 machine (test-macstadium-macos1013-x64-1): https://ci.adoptopenjdk.net/job/Grinder/6026/ - all PASSED except for
cmdLineTester_modularityddrtests_0
Raised new issue: https://github.com/eclipse/openj9/issues/11739 (common with x86-64_mac)

xlpCodeCacheTests_0
xlpCodeCacheTests_1
Already raised defect https://github.com/eclipse/openj9/issues/11171. Fixed (test fix) but the fix was not merged into the openj9-0.24.0 release.

x86-64_windows
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.functional_x86-64_windows/60/consoleFailed target:
shrtest_win_1
Raised https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1859
Rerun on different test machine: https://ci.adoptopenjdk.net/job/Grinder/6019/ - PASSED

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_x86-64_windows/60/consoleFull
Failed targets:
cmdLineTester_classesdbgddrext_1
cmdLineTester_shrcdbgddrext_1
Already known issue: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1819
Rerun on different test machine: https://ci.adoptopenjdk.net/job/Grinder/6020/
Passed
x86-64_windows_xl
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.functional_x86-64_windows_xl/64/consoleFull
Failed target:
cmdLineTester_callsitedbgddrext_openj9_0
Already known issue: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1819
Rerun on different test machine: https://ci.adoptopenjdk.net/job/Grinder/6022/ - PASSED

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_xl/156/console
Failed targets / tests:
jdk_foreign_1
TEST: java/foreign/TestMismatch.java
Test got OOM running on test-azure-win2012r2-x64-2
Rerun on different machine (test-aws-win2019-x64-1): https://ci.adoptopenjdk.net/job/Grinder/6023/
Passed

**Comment by andrew-m-leonard** [comment] 2021-01-22 16:10
**Hilighting issues:**

**ppc64_aix**
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/172/console
Failed target / test:
jdk_lang_j9_0
TEST: java/lang/ProcessBuilder/Basic.java#id0
Re-run: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/174/
Raised issue: https://github.com/eclipse/openj9/issues/11738

**x86-64_linux**
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_x86-64_linux/162/console
Failed targets / tests:
jdk_foreign_0
TEST: java/foreign/TestMismatch.java
Raised new issue: https://github.com/eclipse/openj9/issues/11732

https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_x86-64_linux/64/console
Failed target:
testDDRExt_Class_0
Raised new issue: https://github.com/eclipse/openj9/issues/11733

**x86-64_mac**
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.functional_x86-64_mac/61/
Failed targets:
cmdLineTester_callsitedbgddrext_openj9_0
cmdLineTester_pltest_osx_0
cmdLineTest_sigabrtHandlingTest_0
Rerun on pre mac 10.14 machine (test-macstadium-macos1013-x64-1): https://ci.adoptopenjdk.net/job/Grinder/6017/ - Tests PASSED except for
     cmdLineTest_sigabrtHandlingTest_0
UnsatisfiedLinkError: Can't load gptest
Issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2178
Re-run on 1010: https://ci.adoptopenjdk.net/job/Grinder/6034/console
Passed

cmdLineTester_modularityddrtests_1
Re-run: https://ci.adoptopenjdk.net/job/Grinder/6033/
Raised new issue: https://github.com/eclipse/openj9/issues/11739

**Comment by smlambert** [comment] 2021-01-22 16:27
Thanks for the summary @andrew-m-leonard 
Given those are all known/identified items (many related to config issues, and/or machine capabilities)

Thumbs up from me to release/publish 👍

**Comment by andrew-m-leonard** [comment] 2021-01-22 16:31
Thanks @smlambert 
Just waiting for last AIX re-run to finish shortly: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_ppc64_aix/66/

**Comment by andrew-m-leonard** [comment] 2021-01-22 16:39
Re-running AIX extended.functional failures without -Xmx2g: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_ppc64_aix/67/
**All Passed**

**Comment by pshipton** [comment] 2021-01-22 17:43
jdk15 OpenJ9 issues.
eclipse/openj9#11738 - test/machine issue
eclipse/openj9#11732 - test/machine issue
eclipse/openj9#11733 - we've seen this before, likely a test issue, not a blocker
eclipse/openj9#11739 - a little concerning, likely related to DDR and not the VM, so not a blocker. I'm waiting to get the core so I can look.

**Comment by andrew-m-leonard** [comment] 2021-01-22 18:35
@AdoptOpenJDK/tsc Request to publish please?

**Comment by pshipton** [comment] 2021-01-22 18:45
eclipse/openj9#11739 is caused by running the wrong test material. It's running the head stream tests against a 0.24.0 release build.

**Comment by andrew-m-leonard** [comment] 2021-01-22 19:03
Binaries: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk-15.0.2+7_openj9-0.24.0

**Comment by karianna** [comment] 2021-01-27 15:33
@lumpfish can this be closed now?

**Comment by sxa** [comment] 2021-01-27 17:21
Yes it can :-)

**Closed as completed by sxa** 2021-01-27 17:21 UTC
Labels: enhancement
