### ISSUE TITLE
Make an rss feed of releases 

### ISSUE THREAD

**Issue by jamesbroadhead** [AdoptOpenJDK/TSC#33] opened 2018-09-13 21:04 UTC
Ideally, one for each major JDK version (but a single feed would work too)

**Comment by gdams** [comment] 2019-01-11 10:00
github releases actually has a built in RSS feed. E.g https://github.com/AdoptOpenJDK/openjdk8-binaries/releases.atom

**Comment by jamesbroadhead** [comment] 2019-01-11 12:57
Hi @gdams -- thanks for the response! 

That feed isn't all that useful, as it contains nightlies -- what would be really nice would be a feed for stable releases only

**Comment by gdams** [comment] 2019-01-11 15:45
is the api not suitable for this? https://api.adoptopenjdk.net/

**Comment by jamesbroadhead** [comment] 2019-01-18 11:08
@gdams  it's ok, but not ideal. 

Our main need is "has a new major JDK version been released". 
eg. 8u192 -> 8u202 

I'll build an API client for this purpose (but a "stable releases" rss feed would be nicer!)

**Comment by gdams** [comment] 2019-01-18 11:14
@jamesbroadhead try https://api.adoptopenjdk.net/v2/info/releases/openjdk8 . That should return all the release versions.

**Comment by johnoliver** [comment] 2019-01-18 11:17
Also there is:

https://api.adoptopenjdk.net/v2/latestAssets/releases/openjdk8

That gives the most recent asset for every platform we produce.

If you want rss(ish) and if your rss client can do atom:

```
curl -H "Accept: application/atom+xml" https://github.com/AdoptOpenJDK/openjdk8-binaries/releases
```

**Comment by breun** [comment] 2019-01-21 12:45
I'm a package maintainer for MacPorts and and among the packages I maintain are the AdoptOpenJDK packages. I use RSS/Atom release feeds for all packages I maintain so I know when to update packages, but https://github.com/AdoptOpenJDK/openjdk8-binaries/releases also contains all nightly builds, which makes it kind of unusable for my use case. An RSS/Atom version of https://api.adoptopenjdk.net/v2/latestAssets/releases/openjdk8 would be great.

**Comment by breun** [comment] 2019-07-14 00:41
I think this issue is a duplicate of https://github.com/AdoptOpenJDK/openjdk-website/issues/350

**Comment by hege-li** [comment] 2020-08-20 08:23
You can use service like https://siftrss.com/ to proxy filter any feed. For example to not include content that includes "Nightly".

**Comment by arend-von-reinersdorff** [comment] 2020-08-20 11:52
@hekeli thanks for the hint :-) Here's a feed with "Nightly" excluded:
https://siftrss.com/f/DkkAvB7VdPQ

I'd still prefer an official release feed. In my experience, these feed filtering services come and go over the years.

**Comment by karianna** [comment] 2020-08-27 11:00
Closing this as a duplicate - the TSC certainly won't stop anyone from building this :-)

**Closed as completed by karianna** 2020-08-27 11:00 UTC
Labels: duplicate, enhancement
