### ISSUE TITLE
Promote AdoptOpenJDK Version 11.0.8+10 (GA)

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#161] opened 2020-07-15 12:25 UTC
Java Version:
11.0.8+10

JVM:
- [x] OpenJ9
- [x] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by gdams** [comment] 2020-07-15 12:29
TRSS Link: https://trss.adoptopenjdk.net/buildDetail?parentId=5f0ec5177eaab3443ca8322c&testSummaryResult=failed&buildNameRegex=%5ETest.*

### Test Failures - Hotspot

**Test_openjdk11_hs_extended.system_ppc64_aix**
MathLoadTest_all_0 => long term failure https://github.com/AdoptOpenJDK/TSC/issues/132#issuecomment-575217309
LockingLoadTest_0 => long term failure https://github.com/AdoptOpenJDK/TSC/issues/132#issuecomment-575217309

**Test_openjdk11_hs_extended.system_x86-64_mac**
HCRLateAttachWorkload_previewEnabled_0 => long term failure https://github.com/AdoptOpenJDK/openjdk-tests/issues/1555

**Test_openjdk11_hs_sanity.external_x86-64_linux_openliberty-mp-tck**
openliberty_microprofile_tck_0 => long term failure https://github.com/AdoptOpenJDK/TSC/issues/152#issuecomment-614107570

**Comment by karianna** [comment] 2020-07-15 14:27
I approve `11.0.8+10` release for Hotspot builds.

**Comment by smlambert** [comment] 2020-07-15 14:28
As those failures have been carried over across from several releases, I would like to see them investigated/understood and resolved in time for next release. 

Can you create issues for MathLoadTest_all / LockingLoadTest and put on the top priority list?  

https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1274 which is ultimately the issue for HCRLateAttachWorkload_previewEnabled failure, is already marked as top priority.

**Comment by smlambert** [comment] 2020-07-15 21:47
OpenJ9 jdk-11.0.8+10_openj9-0.21.0

EA builds for aarch64 (pipeline [1086](https://trss.adoptopenjdk.net/buildDetail?parentId=5f0f11487eaab3443ca86a64) and [1088](https://trss.adoptopenjdk.net/buildDetail?parentId=5f0f2ab17eaab3443ca88ce5)):
**Test_openjdk11_j9_sanity.openjdk_aarch64_linux** - 1 failure, jdk_util / ReduceTest (appears 'new',  [crash](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/203/) then test times out, [console output](https://trss.adoptopenjdk.net/output/test?id=5f0f44f17eaab3443ca8d930)) - EA release, so non-blocking (noted here: https://github.com/eclipse/openj9/issues/10168#issuecomment-659107152)

Test pipelines on ppc64le and ppc64le_xl failed to download jtreg (issue opened here: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1894), rerun of test pipelines here:
**Test_openjdk11_j9_sanity.openjdk_ppc64le_linux** [293](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux/293) - all pass
**Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl** [192](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl/192) - all pass

**Test_openjdk11_j9_sanity.openjdk_ppc64_aix** - jdk_util_j9_0 / Zip64SizeTest failure - most definitely a machine issue, only reproducible on 1 AIX machine: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1879

Disabling [build-osuosl-aix71-ppc64-1](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/) to rerun sanity.system target in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_ppc64_aix/10 (**Update**: all pass), since all tests fail with message: 
```
[2020-07-15T17:29:59.332Z] There must be at least 3Gb (3072Mb) free to be sure of capturing diagnostics
[2020-07-15T17:29:59.332Z] files in the event of a test failure.
```

**Test_openjdk11_j9_sanity.system_x86-64_linux** - [7 jlm targets fail ](https://trss.adoptopenjdk.net/allTestsInfo?buildId=5f0f4eaf7eaab3443ca8f618&limit=5&hasChildren=false)(TestJlmRemoteMemoryAuth_0, TestIBMJlmRemoteMemoryAuth_0, TestJlmRemoteMemoryNoAuth_0, TestIBMJlmRemoteMemoryNoAuth_0, TestIBMJlmRemoteClassAuth_0, TestJlmRemoteClassNoAuth_0, and TestIBMJlmRemoteClassNoAuth_0) - seen before, appears to be a network issue on the machine (see https://github.com/eclipse/openj9/issues/10156), will rerun here: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_linux/289

**Test_openjdk11_j9_sanity.openjdk_x86-64_mac_xl** - jdk_util / TestCleaner - known intermittent issue considered non-blocking, https://github.com/eclipse/openj9/issues/8872

**Comment by karianna** [comment] 2020-07-15 22:28
> As those failures have been carried over across from several releases, I would like to see them investigated/understood and resolved in time for next release.
> 
> Can you create issues for MathLoadTest_all / LockingLoadTest and put on the top priority list?
> 
> [AdoptOpenJDK/openjdk-infrastructure#1274](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1274) which is ultimately the issue for HCRLateAttachWorkload_previewEnabled failure, is already marked as top priority.

@d3r3kk was kindly on the case for capturing the other failing tests.  They're not P0/P1's but hopefully, with our extra internal infra we can now start splitting out infra vs 'real' failures on these

**Comment by lumpfish** [comment] 2020-07-16 08:12
**Test_openjdk11_j9_sanity.system_x86-64_linux** rerun (https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_linux/289) - all tests passed.

**Comment by sxa** [comment] 2020-07-16 08:51
Approved for OpenJ9 as per slack discussion

**Closed as completed** 2020-09-16 09:02 UTC
Labels: enhancement
