### ISSUE TITLE
Promote AdoptOpenJDK Version 8u222 (GA), 11.0.4 (GA), 12.0.2 (GA)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#99] opened 2019-07-16 20:37 UTC
# Release Order

We will release the following versions/platforms in the order listed below although this may be subject to change on the day of the release.

Please see the #release channel in the adoptopenjdk.net/slack for coordination efforts.

## jdk8u222-b10 - Phase 1

**Hotspot JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

**OpenJ9 JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

----

## 11.0.4+11 - Phase 1

**Hotspot JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

**OpenJ9 JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

----

## 12.0.2+10 - Phase 1

**Hotspot JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

**OpenJ9 JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

----

##  jdk8u222-b10 - Phase 2

**Hotspot JVM**
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] s390xLinux
- [x] sparcv9Solaris
- [x] x64Solaris
- [x] arm32Linux

**Hotspot JVM**
- [x] aarch64Linux

**OpenJ9 JVM:**
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] 390xLinux
- [x] linuxXL
- [x] x64MacXL
- [x] x64WindowsXL

----

##  11.0.4+11 - Phase 2

**Hotspot JVM**
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] s390xLinux
- [x] aarch64Linux
- [x] arm32Linux

**OpenJ9 JVM:**
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] 390xLinux
- [x] linuxXL
- [x] x64MacXL
- [x] x64WindowsXL

----

##  12.0.2+10 - Phase 2

**Hotspot JVM**
- [x] x32Windows
- [ ] ppc64Aix
- [x] ppc64leLinux
- [x] s390xLinux
- [x] aarch64Linux
- [x] arm32Linux

**OpenJ9 JVM:**
- [ ] ppc64Aix
- [x] ppc64leLinux
- [x] 390xLinux
- [x] linuxXL
- [x] x64MacXL
- [x] x64WindowsXL

**Comment by jerboaa** [comment] 2019-07-16 21:06
JDK 8 GA: 8u222-b10
JDK 11 GA: 11.0.4+11
JDK 12 GA: 12.0.2+10

**Comment by karianna** [comment] 2019-07-17 09:25
13 isn't out until Sept - so removed those.

**Comment by karianna** [comment] 2019-07-17 13:52
# PostMortem

- Can we speed up tests by a combination of splitting test suites across hosts or simply getting more powerful hardware?
- Need to think about a completely locked down env to test any embargoed patches so we don't just see them for the first time when the GA tag comes out
- Can we globally disable all cron jobs on Jenkins?
- Stabilize machine layer before the day of release (macs and windows machines added JIT, lack soaking period to see how they perform)
- More AIX and 'lesser' platform hosts required else the whole pipeline gets held up (from a user experience perspective, we could run 1 job pipelines which would speed releases of individual platforms up - but it's easier / better to do the whole lot in one.
- Some test jobs failed due to timeouts which error the agent.  This hangs the job which hangs the pipeline.
- Need far more robust hosts on the secondary platforms - end users will need to contribute else we should consider dropping support for them
- Add Homebrew and Docker to the release pipelines (related https://github.com/AdoptOpenJDK/openjdk-tests/issues/773, https://github.com/AdoptOpenJDK/openjdk-tests/issues/1109 and https://github.com/AdoptOpenJDK/openjdk-build/issues/1123)

**Comment by smlambert** [comment] 2019-07-17 14:22
Test Analysis Hotspot JVM - jdk8

**x64Linux**

- [x] sanity.openjdk - pass
- [x] sanity.system - 1 failure (TestJlmRemoteMemoryNoAuth_SE80_Linux reproducible in [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1793/tapResults/)), [10x grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1798/) - 9/10 iterations passing, will mark as non-blocking
- [x] extended.system - pass
- [x] sanity.perf - pass
- [x] sanity.external - 1 failure (tomee microprofile tcks - non-blocking, first fail 3 days ago, will investigate)

**x64Mac**

- [x] sanity.openjdk - 2 failures (likely machine issue, ports in use, pass on non-newly added mac in this [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1792/))
- [x] sanity.system - 1 failure (TestJlmRemoteMemoryNoAuth_SE80 - [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1794) - passed on test-macincloud-macos1013-x64-1)
- [x] extended.system - 1 failure (HCRLateAttachWorkload [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1795)) - not reproducible in 2nd [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1801/) running on test-macincloud-macos1010-2 - either intermittent or machine issue, will investigate further but marking as not blocking

**x64Windows**

- [x] [sanity.openjdk](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/7/testReport/) - 1 failure (jdk_util: java/util/Locale/LocaleProviders.sh) - reproduced in [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1796/) on test-azure-win2012r2-x64-1, reran on internal machine without failure.
- [x] sanity.system - passes
- [x] extended.system - passes

**x32Windows**
- [x]  sanity.openjdk - 1 failure (jdk_util: java/util/Locale/LocaleProviders.sh same as x64)

**ppc64leLinux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**s390xLinux**
- [x] sanity.openjdk - [5 failures](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/6/testReport/) 
- [x] sanity.system - pass
- [x] extended.system - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.system_s390x_linux/2/tapResults/) (UtilLoadTest)

**ppc64Aix**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**aarch64Linux**
- [x] sanity.openjdk - [2 failures](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_aarch64_linux/5/testReport/) - timeouts (need to be calibrated, outrageously long factor)
- [x] sanity.system - pass
- [x] extended.system - pass

**Comment by smlambert** [comment] 2019-07-17 17:26
Test Analysis Hotspot JVM - jdk11

**x64Linux**

- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass
- [x] special.functional - pass
- [x] sanity.perf - pass
- [x] sanity.external - pass

**x64Mac**

- [x] sanity.openjdk - [6 failures](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_mac/7/testReport/) will rerun on separate machine to see if recur  
- 2 of the 6 failures (in jdk_lang and jdk_util targets) fail in similar way (also seen in jdk8 failure)
java.io.IOException: well-known file /var/folders/h1/b_v48zpd1zd54jblxnx58p3r0000gr/T/.java_pid73679 is not secure: file's group should be the current group (which is -1) but the group is 0
- [x] sanity.system - pass
- [x] extended.system - pass
- [x] sanity.perf - expected compile fail (non-blocking, job updated, rerun & passes [here](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-64_mac/8/)

**x64Windows**

- [x] sanity.openjdk - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/7/testReport/) (socket in use, will retry on different machine, [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1805/) - non-blocking)
- [x] sanity.system - pass
- [x] extended.system - pass

**x32Windows**
- [x] sanity.openjdk - [2 failures](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/7/testReport/) - non-blocking

**ppc64Aix**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system  - pass

**aarch64Linux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**ppc64leLinux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass
- [x] sanity.perf - pass

**Comment by karianna** [comment] 2019-07-17 20:43
> Test Analysis Hotspot JVM - jdk11
<snip>

After chatting to @smlambert - I'm comfortable with the failing tests for Mac OS X, Windows and Linux x86 with regards to the release quality and will publish.

**Comment by karianna** [comment] 2019-07-17 21:00
> Test Analysis Hotspot JVM - jdk8
<snip>

After chatting to @smlambert - I'm comfortable with the failing tests for all of the platforms with regards to the release quality and will publish.

**Comment by smlambert** [comment] 2019-07-18 02:00
Test Analysis OpenJ9 JVM - jdk8

**x64Linux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass
- [x] sanity.perf - pass
- [x] sanity.external - 2 failures (tomee microprofile tck same as hotspot, [thorntail-mp-tck](https://github.com/eclipse/openj9/issues/6435)) - marking this as non-blocking (but we need to triage and report both)
- [x] special.functional - pass

**x64Linux_XL**
- [x]  sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**ppc64Aix**  - sick machine [build-osuosl-ppc64-aix-71-1](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-1/) - will run at ci.eclipse.org/openj9 while its being fixed
- [x] sanity.openjdk - [grinder](https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/455) passes
- [x] sanity.system
- [x] extended.system 

**x64Mac**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass 
- [x] extended.system - 1 failure (SharedClassesAPI_0 - not included in HS set, passing at ci.eclipse.org/openj9)

**x64Mac_XL**
- [x] sanity.openjdk - [7 failures](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/7/testReport/) - all jdk_net failures  - [grinder](https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/454) rerun passes on different machine, non-blocking, known issue with testing on Mac10.14: eclipse/openj9#6035, same set fail with hotspot : internal Grinder_Advanced/330
- [x] sanity.system - pass
- [x] extended.system - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_mac_xl/2/tapResults/) - SharedClassesAPI_0 same as x64Mac, passing at ci.eclipse.org/openj9

**x64Windows**
- [x] sanity.openjdk - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows/6/testReport/) (on some machines, java/util/Locale/LocaleProviders.sh same as hotspot), non-blocking
- [x] sanity.system
- [x] extended.system 

**x32Windows**
- [x] sanity.openjdk - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/6/testReport/) same as Hotspot (non-blocking)

**ppc64leLinux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**s390xLinux**
- [x] sanity.openjdk - [1 failure ](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/7/testReport/)(non-blocking, java/nio/channels/Selector/LotsOfChannels.java)
- [x] sanity.system - 8 failures - all JLMRemoteMemory/Class tests with connection issues (will rerun on different machine, passes at ci.eclipse.org/openj9) - [grinder](https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/456) rerun passes
- [x] extended.system - pass

**Comment by smlambert** [comment] 2019-07-18 02:28
Test Analysis OpenJ9 JVM - jdk11

**x64LInux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass 
- [x] extended.system - pass 
- [x] sanity.perf - pass
- [x] sanity.external - pass
- [x] special.functional - pass

**x64LInux_XL**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**x64Mac**
- [x] sanity.openjdk - [2 failures](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/7/testReport/) - non-blocking 
- [x] sanity.system - pass
- [x] extended.system - [2 failures](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/1/tapResults/) (SharedClassesAPI [grinder-1](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1823), [-2](https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/459), SharedClasses.SCM23.MultiThread [grinder-1](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1824), [-2](https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/460) both pass) - passes in runs at ci.eclipse.org/openj9

**x64Mac_XL**
- [x] sanity.openjdk - [5 failures](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_xl/7/testReport/) - non-blocking ([grinder-1](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1826)) passes (run on test-macincloud-macos1014-x64-2)
- [x] sanity.system - pass
- [x] extended.system - [1 failure ](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac_xl/1/tapResults/) - same as jdk8, SharedClassesAPI_0 (passing at ci.eclipse.org/openj9)

**x64Windows**
- [x] sanity.openjdk - [1 failure ](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/7/testReport/) - socket in use, non-blocking (passes on different machine, internal Grinder_Advanced/334)
- [x] sanity.system - pass
- [x] extended.system - pass

**x64Windows_XL**
- [x] sanity.openjdk - [2 failures](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl/2/testReport/) - BitSetStreamTest [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1820/) passes, non-blocking
- [x] sanity.system - pass

**s390xLinux**
- [x] sanity.openjdk - [7 failures](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux/7/testReport/) - connection issues / timeouts
- [x] sanity.system - still running (expect to see connection issues on -XJ machine, passes at ci.eclipse.org/openj9)
- [x] extended.system - pass

**ppc64Aix** - aix test machine down, will run at ci.eclipse.org/openj9
- [x] sanity.openjdk - [grinder](https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/458) run
- [x] sanity.system
- [x] extended.system 

**ppc64leLinux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**Comment by smlambert** [comment] 2019-07-18 20:13
Test Analysis Hotspot JVM - jdk12

**x86Windows**
- [x] sanity.openjdk - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_sanity.openjdk_x86-64_windows/2/testReport/) - non-blocking (java/net/DatagramSocket/ReuseAddressTest.java address in use)
- [x] sanity.system - pass
- [x] extended.system - pass

**x86Linux**
- [x] sanity.openjdk - pass
- [x] sanity.system - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_sanity.system_x86-64_linux/2/tapResults/) -  TestJlmRemoteMemoryAuth_0, non-blocking same as jdk8
- [x] extended.system - pass

**x86Mac**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_extended.system_x86-64_mac/2/tapResults/) - HCRLateAttachWorkload_0 (same as jdk8, non-blocking)

**x32Windows**
- [x] sanity.openjdk - [2 failures](https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_sanity.openjdk_x86-32_windows/3/testReport/) - non-blocking

**ppcle64Linux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**s390xLinux**
- [x] sanity.openjdk 
- [x] sanity.system - pass
- [x] extended.system - pass

**aarch64Linux**
- [x] sanity.openjdk - pass
- [x] sanity.system - [3 failures](https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_sanity.system_aarch64_linux/2/tapResults/) need investigation (MauveSingleThreadLoadTest_HotSpot, MauveSingleInvocationLoadTest_HotSpot, MauveMultiThreadLoadTest_HS)
- [x] extended.system - [2 failures](https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_extended.system_aarch64_linux/2/tapResults/) that need investigation (MathLoadTest, LockingLoadTest)

Waiting on good builds for **arm32** and **ppc64Aix**

**Comment by smlambert** [comment] 2019-07-19 00:24
Test Analysis OpenJ9 JVM - jdk12

**x64Windows**
- [x] sanity.openjdk - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_sanity.openjdk_x86-64_windows/2/testReport/) - non-blocking (ReuseAddressTest)
- [x] sanity.system - pass
- [x] extended.system - pass

**x64WindowsXL**
- [x] [sanity.openjdk](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk12_j9_sanity.openjdk_x86-64_windows_xl/2) - 2 failures ([grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1828) to determine machine/test issue passes on test-godaddy-win2016-x64-2)
- [x] [sanity.system ](https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk12_j9_sanity.system_x86-64_windows_xl/4)
- [x] [extended.system](https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk12_j9_extended.system_x86-64_windows_xl/1) - pass

**s390xLinux**
- [x] sanity.openjdk - [6 failures](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_sanity.openjdk_s390x_linux/2/testReport/) - jdk_net, non-blocking
- [x] sanity.system - pass
- [x] extended.system - pass

**x64Mac**
- [x] sanity.openjdk - 3 failures (comm. errors seen before, non-blocking)
- [x] sanity.system - pass
- [x] extended.system - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_extended.system_x86-64_mac/2/tapResults/) (SharedClassesAPI, non-blocking)

**x64MacXL**
- [x] sanity.openjdk - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_sanity.openjdk_x86-64_mac_xl/3/testReport/) (non-blocking)
- [x] sanity.system - pass
- [x] extended.system - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_extended.system_x86-64_mac_xl/2/tapResults/) (SharedClassesAPI, non-blocking)

**x64Linux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - [1 failure](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_extended.system_x86-64_mac/2/tapResults/) (SharedClassesAPI, non-blocking)

**x64LinuxXL**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**ppc64leLinux**
- [x] sanity.openjdk - pass
- [x] sanity.system - pass
- [x] extended.system - pass

**ppc64Aix** build failed for a [known reason](https://ci.eclipse.org/openj9/job/Build_JDK12_ppc64_aix_OpenJDK12/14)
SharedClassesAPI failure is due to a machine config issue (memory mapped shared memory should get [increased](https://stackoverflow.com/questions/2017004/setting-shmmax-etc-values-on-mac-os-x-10-6-for-postgresql))

**Comment by dinogun** [comment] 2019-07-19 08:25
Prereq builds needed for updating the [Official](https://hub.docker.com/_/adoptopenjdk) Docker Images.

## jdk8u222-b10

**Hotspot JVM**

- [x] x64Linux
- [x] ppc64leLinux
- [x] s390xLinux
- [x] x64Windows
- [x] arm32Linux

**OpenJ9 JVM**

- [x] ppc64leLinux
- [x] s390xLinux
- [x] x64Linux
- [x] x64Windows

---

## 11.0.4+11

**Hotspot JVM**

- [x] x64Linux
- [x] ppc64leLinux
- [x] s390xLinux
- [x] aarch64Linux
- [x] x64Windows
- [x] arm32Linux

**OpenJ9 JVM**

- [x] ppc64leLinux
- [x] s390xLinux
- [x] x64Linux
- [x] x64Windows

---

## 12.0.2+10

**Hotspot JVM**

- [x] x64Linux
- [x] ppc64leLinux
- [x] s390xLinux
- [x] aarch64Linux
- [x] x64Windows
- [x] arm32Linux

**OpenJ9 JVM**

- [x] ppc64leLinux
- [x] s390xLinux
- [x] x64Linux
- [x] x64Windows

**Closed as completed** 2020-08-08 10:22 UTC
Labels: enhancement
